### ISSUE TITLE
implicit left-join in horizons()<- bug / tests needed

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#105]
I noticed that horizon data were being silently re-ordered when assigning a new horizon-level attribute. This only happens when using profile IDs that aren't pre-sorted before SPC init: very common when working with NASIS or KSSL data where IDs are generated from integer sequences that have been converted into character-class data.

```r
# 1.18.3 (pre 2020-01-06)
library(aqp)

# IDs that when sorted will no be in this order
s <- c('a', "1188707", "1188710", "120786", "1207894", 'z')
l <- lapply(s, random_profile)
d <- do.call('rbind', l)

# init SPC
depths(d) <- id ~ top + bottom

## !! bug happens here, when attempting to set a new horizon-level attr
## call stack roughly
# $<-
# horizons<-
# merge(old, new)
d$zzz <- rep(NA, times=nrow(d))

# previously mysterious warning message
z <- d[1:5, ]

# ordering of profile IDs (unique, from @horizons) != ordering of IDs in @site
all(profile_id(d) == site(d)[[idname(d)]])
```

Would it be possible to double-check the following? I added ` sort=FALSE` to `merge()`, and I think that it solved the problem. However, I can't be sure that the following code is always "doing the right thing".

From /R/setters.R:
```r
  # NEW: more extensive test of ids -- is it possible to merge rather than replace?
  if(hzidname(object) %in% names(value)) {
    # if hzidname for the SPC is present in the new data,
    
    # only merge if all horizon IDs in the SPC are also present in the new data
    #   and there are new columns in value that are not in horizons already
    if((length(setdiff(unique(as.character(value[[hzidname(object)]])), hzID(object))) == 0) &
       any(!unique(names(value)) %in% unique(names(object@horizons)))) {
      to_merge <- c(names(value)[!names(value) %in% names(object@horizons)], idname(object), hzidname(object))
      object@horizons <- merge(object@horizons, value[,to_merge], all.x = TRUE, by = c(idname(object), hzidname(object)), sort=FALSE)
      
      # now, do updates to "old" columns so we do not duplicate
      to_update <- names(value)[!names(value) %in% to_merge]
      object@horizons[,to_update] <- value[match(object@horizons[,hzidname(object)], value[,hzidname(object)]), to_update]
      return(object)
    }
  }
```

**Comment by dylanbeaudette** [comment]
I'm pretty sure that this is fixed in 1.18.4.

**Comment by brownag** [comment]
After updating to 1.18.4 I also find that this bug is fixed using the above example code.

```
> # ordering of profile IDs (unique, from @horizons) != ordering of IDs in @site
> all(profile_id(d) == site(d)[[idname(d)]])
[1] TRUE
```

Thanks for catching this -- I don't think I realized that `merge()` sorts by default and that sorting certainly wasn't my intention.

Added your example code as a test in commit 3a1d4c0

**Comment by MollicMeyer** [comment]
I think this issue is still occurring in development and stable versions. 

`mlras <- c('103', '102C', '107A', '107B', '108D', '109', '108C', '115C', '104', '105')
ncss_ia <- fetchKSSL(mlra = mlras, returnMorphologicData = TRUE, simplifyColors = TRUE)

ncss <- ncss_ia$SPC
all(profile_id(ncss) == site(ncss)[[idname(ncss)]])
#False 
`

**Comment by brownag** [comment]
@MollicMeyer 
I believe this is fixed in the latest versions available on GitHub (1.24). 

Running this code using aqp 1.24 and soilDB 2.5.8, I get:

```
utils::packageVersion("aqp")
utils::packageVersion("soilDB")

library(aqp)
library(soilDB)

mlras <- c('103', '102C', '107A', '107B', '108D', '109', '108C', '115C', '104', '105')
ncss_ia <- fetchKSSL(mlra = mlras, returnMorphologicData = TRUE, simplifyColors = TRUE)
  # |==========================================================================================================| 100%
# mixing dry colors ... [546 of 4452 horizons]
# mixing moist colors ... [6202 of 32090 horizons]
# 4335 pedons loaded (27.37 Mb transferred)
# Warning messages:
# 1: Horizon top depths contain NA! Check depth logic with aqp::checkHzDepthLogic() 
# 2: Horizon bottom depths contain NA! Check depth logic with aqp::checkHzDepthLogic() 
ncss <- ncss_ia$SPC

all(profile_id(ncss) == site(ncss)[[idname(ncss)]])
# TRUE
```

We are extremely overdue for a CRAN release -- the aqp version on CRAN (1.19.01) is bugged. We are actively working to get a new version pushed up there. In the meantime, install from GitHub using below commands Be sure that you do this in a fresh install to avoid errors in install.

```
remotes::install_github('ncss-tech/aqp', dependencies=FALSE)
remotes::install_github('ncss-tech/soilDB', dependencies=FALSE)
```

**Comment by MollicMeyer** [comment]
Thanks @brownag ill try again with the git version. I may have not restarted the session properly or something.

**Comment by dylanbeaudette** [comment]
Thanks both of you for the kick in the seat to get a CRAN release out ASAP.
